Blogging/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import index,register,login_view,post,changeProfile,userPosts,logout_view,deletePost,updatePost
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,{'page_no':1},name="home"), 
    path('page/<int:page_no>/', index,name="Home"),
 # For root URL '/'
     # Capture group for optional number
    path('login/',login_view,name='login'),
    path('register/',register,name='register'),
    path('logout/',logout_view,name='logout'),
     path('create-post/',post,name="create-post"),
    path('change-profile/',changeProfile,name="change-profile"),
    path('related-posts/',userPosts,name="user_posts"),
    path('delete-post/<int:id>/',deletePost),
    path('update-post/<int:id>/',updatePost),
    # rest passsword

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name='password_reset_complete'),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib import admin
class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profiles/%y/%m/%d',default='profiles/default.jpg')

from ckeditor.fields import RichTextField
class CreatePost(models.Model):
    title=models.CharField(max_length=300,blank=False)
    content = RichTextField()
    created_at=models.DateField(auto_now_add=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.title
    class Meta:
        ordering=["-created_at"]



# Optionally, you can create a custom admin class
class CreatePostAdmin(admin.ModelAdmin):
    list_display = ('title', 'author', 'created_at')  # Columns to display in the list view
    search_fields = ('title', 'author__username')  # Fields to include in the search box
    list_filter = ('created_at', 'author')  # Filters available in the right sidebar
    ordering = ('-created_at',)  # Default ordering in the admin list view
    fields = ('title', 'content', 'author')  # Fields to display in the detail view

# Register your model with the custom admin class
admin.site.register(CreatePost, CreatePostAdmin)

blog/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile,CreatePost
# from ckeditor.widgets import CKEditorWidget

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    profile_pic=forms.ImageField(required=False)
    
    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
        return email
class LoginForm(forms.Form):
    username=forms.CharField(required=True)
    password=forms.CharField(widget=forms.PasswordInput)
    
class updateProfile(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=['profile_pic']


class Create_Post(forms.ModelForm):
  
    class Meta:
        model=CreatePost
        fields=['title','content']


class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=["username","first_name","last_name"]

blog/views.py
# accounts/vi# accounts/views.py

from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseBadRequest
from django.contrib.auth import login,logout, authenticate
from django.contrib.auth.models import User
from django.http import JsonResponse
from .models import UserProfile,CreatePost
from .forms import CustomUserCreationForm,LoginForm,updateProfile,UserForm,Create_Post
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()

            # Retrieve the image file from the form
            profile_pic = form.cleaned_data.get('profile_pic')
            

            # Create UserProfile instance
            if profile_pic:
               UserProfile.objects.create(user=user, profile_pic=profile_pic)
            else:
                UserProfile.objects.create(user=user)

            # Optionally log the user in after registration
          
            
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                login(request, user)
            return redirect("home")  # Replace 'home' with your desired redirect URL
    else:
        form = CustomUserCreationForm()
    return render(request, 'Register.html', {'form': form})

def login_view(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            password=form.cleaned_data["password"]
            username=form.cleaned_data['username']
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('home')
            else:
                return render(request, "login.html", {"form": form, "error": "Invalid username or password."})
        else:
            return render(request,'login.html',{'form':form,"error":"invalid input"})
    else:
        form=LoginForm()
        return render(request,'login.html',{"form":form})
    

def index(request, page_no=1):  # Default to page 1
    posts = CreatePost.objects.select_related('author', 'author__userprofile').all()
    paginator = Paginator(posts, 2)  # Adjust posts per page as needed

    try:
        page = int(page_no)
    except ValueError:
        return HttpResponseBadRequest('Invalid page number')

    try:
        page_obj = paginator.page(page_no)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        posts_data = [
            {
                'post_id': post.id,
                'title': post.title,
                'content': post.content,
                'author': f"{post.author.first_name} {post.author.last_name}",
                'created_at': post.created_at,
                'profile_pic': post.author.userprofile.profile_pic.url if post.author.userprofile.profile_pic else None
            }
            for post in page_obj.object_list
        ]
        return JsonResponse({
            'posts': posts_data,
            'has_next': page_obj.has_next() if page_obj.has_next() else None,
            'has_previous': page_obj.has_previous() if page_obj.has_previous() else None,
            'next_page_number': page_obj.next_page_number() if page_obj.has_next() else None,
            'previous_page_number': page_obj.previous_page_number() if page_obj.has_previous() else None,
            'page_num': paginator.num_pages,
            'current_page': page_obj.number
        })
    else:
        return render(request, "index.html", {"page": page_obj, "paginator": paginator})
        



from django.contrib.auth.decorators import login_required

@login_required(login_url="/login/")
def post(request):
    
    if request.method=='POST':
        title = request.POST.get('title')# Safer way to access form data
        content = request.POST.get('content')
        author=request.user
        CreatePost.objects.create(title=title,content=content,author=author)
        return redirect('home')
    else:
        form=Create_Post()
        return render(request,'post-create.html',{"form":form})
    
    
@login_required(login_url="/login/")
def changeProfile(request):
    try:
        user_profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=request.user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = updateProfile(request.POST, request.FILES, instance=user_profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully!')
            return redirect('user_posts')  # Replace 'user_posts' with your desired redirect URL
        else:
            messages.error(request, 'There was an error updating your profile. Please check the form and try again.')
    else:
        user_form = UserForm(instance=request.user)
        

    context = {
        'user_form': user_form,
        
        'img_url': user_profile.profile_pic.url if user_profile.profile_pic else None
    }

    return render(request, 'change-profile.html', context)
     
         
@login_required(login_url="/login/")
def userPosts(request):
    
    posts=CreatePost.objects.filter(author=request.user).select_related('author', 'author__userprofile').all()
    return render(request,"user-posts.html",{"posts":posts})
    


def logout_view(request):
    logout(request)
    return redirect('home')


def deletePost(request,id):
    CreatePost.objects.filter(id=id).delete()
    return redirect('home')




def updatePost(request,id):
    post=get_object_or_404(CreatePost,id=id)

    if request.method=='POST':
        form=Create_Post(request.POST,instance=post)
        if  form.is_valid:
            form.save()
           
            return redirect('home')

    else:
        form=Create_Post(instance=post)
        return render(request,'update-post.html',{"form":form})

blog/templates/Register.html
<!-- templates/registration/register.html -->

{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static  'css/custom-css.css' %}">
{% endblock %}
{% block content %}
<div class="container mx-auto mt-10">
    
        <h2 class="text-center text-2xl font-bold text-gray-800 mb-6">Register</h2>
        <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            
            {{ form}}
         
            <button type="submit">Submit</button>
            
        </form>
        
        <!-- {% if form.errors %}
            <div class="mt-4">
                <ul class="text-red-600 text-sm">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ field.label }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %} -->
    </div>

{% endblock %}

blog/templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>blogging Website</title>
    {% tailwind_css %}
       

    
    {% block links %} {% endblock %}
    {% block script %}{% endblock %}
    <script src="https://kit.fontawesome.com/81874f1d71.js" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    
</head>

<body class="bg-gray-100 w-screen relative mx-auto">
    
    {% block content %}
    {% endblock %}

</body>

</html>

blog/templates/change-profile.html
<!-- change-profile.html -->
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/custom-css.css' %}">
{% endblock %}
{% block content %}
<h2 class="text-2xl font-semibold text-gray-800 mb-6 text-center">Change Profile</h2>

{% if messages %}
    <ul class="messages text-center">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form class="bg-white px-8 pt-6 pb-8 mb-4 w-1/2" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div>
        <label for="profile_pic">Profile Pic: Currently:</label>
        {% if img_url %}
            <img class="w-12 h-12 rounded-full hover:scale-150" src="{{ img_url }}" alt="Profile Picture">
        {% else %}
            <p>No profile picture was uploaded.</p>
        {% endif %}
        <label for="id_profile_pic">Change:</label>
        <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic" class="w-full outline-none">
    </div>
    
       
        {{ user_form }}
    
    
    <button type="submit">Update Profile</button>
</form>

{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block script %}<script  src="{% static 'javascript/index.js' %}" defer></script>{% endblock %}
{% block content %}

<!-- Flex container to hold the whole content including footer -->
<div class="flex flex-col mx-auto w-full">

    <!-- Navigation -->
    <nav class="bg-white shadow-md w-full mx-auto ">
        <div class="px-4 py-2 flex justify-between items-center">
            <div class="text-2xl font-bold mb-4">
                <a href="#" class="text-gray-800">Blogify</a>
            </div>
            <div class="hidden md:flex space-x-4">
                <a href="/login/" class="text-gray-600 hover:text-gray-800 hover:underline underline-4 underline-offset-8">Login</a>
                <a href="/create-post/" class="text-gray-600 hover:text-gray-800 hover:underline underline-4 underline-offset-8">Create Post</a>
                <a href="/related-posts/" class="text-gray-600 hover:text-gray-800 hover:underline underline-4 underline-offset-8">See Your Posts</a>
                <a href="{% url 'change-profile' %}" ><img src="{% static 'images/profile_icon.png'%}" alt="" class="block w-8 h-8 rounded-full border-2"></a>
            </div>
            <div class="md:hidden flex items-center" id="menu-bar">
                <button id="menu-btn" class="text-gray-600 focus:outline-none">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
                    </svg>
                </button>
            </div>
        </div>
        <div id="menu" class="md:hidden peer-focus-within:hidden">
            <a href="#" class="block px-4 py-2 text-gray-600 hover:bg-gray-100">About</a>
            <a href="login/" class="block px-4 py-2 text-gray-600 hover:bg-gray-100">Login</a>
            <a href="/create-post/" class="block px-4 py-2 text-gray-600 hover:bg-gray-100">Create Post</a>
            <a href="/related-posts/" class="block px-4 py-2 text-gray-600 hover:bg-gray-100">See Your Posts</a>
            <a href="{% url 'change-profile' %}" class="block px-4 py-2 text-gray-600 hover:bg-gray-100"><img src="{% static 'images/profile_icon.png'%}" alt="" class="block w-8 h-8 border-2 rounded-full"></a>
        </div>
    </nav>

    <!-- Main content area with flex-grow to fill remaining space -->
    <div class="posts w-11/12 mx-auto">
        {% for post in page.object_list %}
        <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 w-full mx-auto mt-10 h-fit">
            <div class="flex items-center mb-4 h-fit">
                {% if post.author.userprofile.profile_pic %}
                <img class="w-12 h-12 rounded-full mr-4" src="{{ post.author.userprofile.profile_pic.url }}">
                {% else %}
                <img class="w-12 h-12 rounded-full mr-4 border-1 bg-gray-300" src="">
                {% endif %}
                <div>
                    <h4>
                        {% if post.author.first_name and post.author.last_name %}
                        {{ post.author.first_name }} {{ post.author.last_name }}
                        {% else %}
                        Unknown
                        {% endif %}
                    </h4>
                    <p class="text-gray-600">{{ post.created_at }}</p>
                </div>
            </div>
            <h3 class="text-2xl font-bold text-gray-800 mb-2">{{ post.title }}</h3>
            <div class="mb-4 h-fit ">{{ post.content|safe }}</div>

        </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    <div class="text-center mb-5">
        <button class="px-2 py-1 bg-blue-500 text-white disabled:bg-gray-400" data-id="{{ page.number }}" id="previous">&lt;</button>
        <span class="page_info font-semibold text-gray-700">{{ page.number }} of {{ paginator.num_pages }}</span>
        <button id="next" class="px-2 py-1 bg-blue-500 text-white disabled:bg-gray-400" data-id="{{ page.number }}">&gt;</button>
    </div>

    <!-- Footer -->
    <footer class="bg-gray-800 py-1 px-4 sm:py-2 w-full mx-auto">
        <div class="container mx-auto flex items-center justify-between">
            <div>
                <h3 class="text-white text-lg sm:font-semibold">Connect with Us</h3>
            </div>
            <div class="flex space-x-4">
                <a href="#" class="text-gray-300 hover:text-white transition duration-300">
                    <i class="fab fa-facebook-square"></i>
                </a>
                <a href="#" class="text-gray-300 hover:text-white transition duration-300">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#" class="text-gray-300 hover:text-white transition duration-300">
                    <i class="fab fa-instagram"></i>
                </a>
            </div>
        </div>
        <div class="text-white text-center mt-3 text-sm">&copy;All rights reserved @ <span class="year">2024</span></div>
    </footer>

</div>

{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static  'css/custom-css.css' %}">
{% endblock %}
{% block content %}
<div class="container mx-auto mt-10">
    
        <h2 class="text-center text-2xl font-bold text-gray-800 mb-6">Login</h2>

        <form method="post" novalidate class="w-full shadow-md">
            {% if error %}
            <p class="text-red-500 text-center">{{error}}
            </p>
            {% endif %}
            {% csrf_token %}
            {{ form}}
            <button type="submit" class="mx-auto  py-3 text-md bg-blue-500 ">Submit</button>
        <p class="text-center mt-5"><a href="{% url 'password_reset' %}" class="cursor-pointer inline-block mt-3 mb-4 text-blue-500 underline">forgot password</a><br><span class="text-gray-500 ">do'nt have account?</span><a href="{% url 'register' %}" class="cursor-pointer hover:underline underline-offset-4  text-blue-500">create account</a><br>
        </p>
        </form>
    </div>
    {% endblock %}

blog/templates/password_reset.html
<!-- templates/registration/password_reset_form.html -->

{% extends "base.html" %}
{% load static%}

{% block links %}
<link rel="stylesheet" href="{% static  'css/custom-css.css' %}">
{% endblock %}

{% block content %}
  <h2 class="text-center text-md ">Password reset</h2>
  <div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="mt-3">Send email</button>
  </form>
  </div>
{% endblock %}

blog/templates/password_reset_complete.html
{% extends "base.html" %}
{% block content %}


<div class="container ">
    <p class="text-center mt-5 text-lg my-10">password has been reset successfully.</p>
    
    <!-- Optionally, provide additional instructions -->
    <div class="text-center mt-3">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold  rounded focus:outline-none focus:shadow-outline" type="submit" value="update picture"><a href="{% url 'login' %}" class="inline-block py-2 px-4">back to login</a></button>
    </div>
    
   </div>

   {% endblock %}

blog/templates/password_reset_confirm.html
<!-- templates/registration/password_reset_form.html -->
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static  'css/custom-css.css' %}">
{% endblock %}
{% block content %}
  <h2 class="text-center text-lg mb-2">Password reset</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="mt-3">Reset password</button>
  </form>
{% endblock %}

blog/templates/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<div class="container mx-auto px-10 py-12 p-5">
    <div class="bg-white shadow-md rounded-lg p-8 md:w-2/3 lg:w-1/2 mx-auto">
        <h2 class="text-2xl font-semibold text-gray-800 mb-6">Password Reset Request Sent</h2>
        <p class="text-gray-600 mb-4 p-5">An email with instructions to reset your password has been sent to the email address you provided. Please check your email and follow the instructions.</p>
        
        <!-- Additional instructions -->
        <p class="text-gray-600">If you don't receive the email within a few minutes, please check your spam or junk folder.</p>
        
        <!-- Optional button to go back to login -->
        <div class="mt-8 text-center">
            <a href="{% url 'login' %}" class="inline-block bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-lg shadow-md transition duration-300 ease-in-out">Go back to login</a>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/post-create.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static  'css/editor-css.css' %}">
{% endblock %}
{% block  content %}
<form method="post" action="/create-post/" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    {{ form}}
    <input class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" value="post"/>
</form>

{% endblock %}

blog/templates/update-post.html
  {% extends 'base.html' %}
   {% load static %}
  
  {% block links %}
  <link rel="stylesheet" href="{% static  'css/editor-css.css' %}">
  {% endblock %}

  {% block content %}


    
    <form action="" method="post">
        {% csrf_token %}
        
    
    {{form}}
    <input type="submit" value="post"> 
   </form>
   <script>
    // For CKEditor
    CKEDITOR.replace('id_content');

   
</script>
{% endblock %}

blog/templates/user-posts.html
 {% extends 'base.html' %}

{% load static %}
{% block script %}<script  src="{% static 'javascript/user-posts.js' %}" defer></script>{% endblock %}
{% block content %}
<nav class="bg-white shadow-md w-full mx-auto">
    <div class=" px-4 py-2 flex justify-between items-center">
        <div class="text-2xl font-bold">
            <a href="#" class="text-gray-800">Blogify</a>
        </div>
        <div class="hidden md:flex space-x-4">
       
        <a href="{% url 'logout' %}" class="text-gray-600 hover:text-gray-800 hover:underline undeline-4 underline-offset-8">Logout</a>
            <a href="{% url 'create-post' %}" class="text-gray-600 hover:text-gray-800 hover:underline undeline-4 underline-offset-8">create post</a></div>
        <div class="md:hidden flex items-center" id="menu-bar">
            <button id="menu-btn" class="text-gray-600 focus:outline-none">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
                </svg>
            </button>
        </div>
    </div>
    <div id="menu" class="md:hidden">
     
        
        <a href="/create-post/" class="block px-4 py-2 text-gray-600 hover:bg-gray-100">create post</a>
        <a href="{% url 'logout' %}" class="block px-4 py-2 text-gray-600 hover:bg-gray-100 ">Logout</a>
       
    </div>
</nav>
{% for post in posts %}
<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 w-full md:w-4/6 mx-auto mt-10">
   <div class=" mb-4 flex justify-between">
    <button class="delete_post font-semibold px-2 py-1  border-2  bg-red-500  rounded  outline-2 focus:outline-blue-900 w-fit text-nowrap text-sm md:text-lg"  data-id={{post.id}}>delete  post</button>
    <button class="update_post font-semibold py-1 px-2 border-2 bg-blue-500 rounded  outline-2  focus:outline-blue-900 w-fit text-nowrap text-sm md:text-lg" data-id={{post.id}}>update post</button>
</div>

    <div class="flex items-center justify-between mb-4">
      <div class="flex-col">
    
    {% if post.author.userprofile.profile_pic %}
   <img class=" w-12 h-12 rounded-full hover:scale-150" src="{{post.author.userprofile.profile_pic.url}}">
   {% else %}
   <img class=" w-12 h-12 rounded-full hover:scale-150 bg-gray-300" src="">
  {% endif %}
   
  
     </div>
    
        <div>
            <h4>
                
            {{post.author.first_name}}  {{post.author.last_name}}
                
            </h4>
            
            <p class="text-gray-600">{{post.created_at}}</p>
        </div>

    </div>
    <h3 class="text-2xl font-bold text-gray-800 mb-2">{{post.title}}</h3>
    <div class="mb-4 h-fit overflow-y-auto">{{ post.content|safe }}</div>
</div>

{% endfor %}
{% endblock %}